## Numpy 살펴보기

### ndarray 객체 생성 및 속성들
1. np.array() 함수

In [2]:
import numpy as np

In [3]:
arr1 = np.array([11, 22, 33])

In [6]:
arr2 = np.array([1, 'A', 0.34])

In [9]:
arr3 = np.array([[0, 0, 0], [0, 0, 0]])

In [15]:
# 0으로 원소값을 초기화 => np.zeros(shape)
#               5행, 2열
arr4 = np.zeros((28, 28), dtype = 'int32')

In [17]:
# 1로 모든 원소값을 초기화 => np.ones(shape)
arr5 = np.ones((5, 2))

In [19]:
# 원하는 숫자(number)로 모든 원소값 초기화 => np.full(shape, number)
arr6 = np.full((2, 3), 255)

In [21]:
# 연속된 범위 지정 원소값 초기화 => np.arange(start, end, step)
arr7 = np.arange(1, 10, 2)

In [24]:
type(arr1), arr1, type(arr2), arr2, type(arr3), arr3, type(arr4), arr4, type(arr5), arr5, type(arr6), arr6, type(arr7), arr7
#                 자동 형변환 -> 문자열

(numpy.ndarray,
 array([11, 22, 33]),
 numpy.ndarray,
 array(['1', 'A', '0.34'], dtype='<U32'),
 numpy.ndarray,
 array([[0, 0, 0],
        [0, 0, 0]]),
 numpy.ndarray,
 array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
         0, 0, 0, 0, 0, 0],
        

2. ndarray 객체 속성

In [5]:
arr1.shape, arr1.ndim, arr1.dtype

((3,), 1, dtype('int32'))

In [26]:
arr1 = np.array([[2, 2, 2], [3, 3, 3]])

In [27]:
arr1

array([[2, 2, 2],
       [3, 3, 3]])

In [29]:
arr1.reshape(6)

array([2, 2, 2, 3, 3, 3])

In [30]:
arr1.reshape(-1)

array([2, 2, 2, 3, 3, 3])

In [31]:
arr1.reshape(-1, 2)

array([[2, 2],
       [2, 3],
       [3, 3]])

In [36]:
arr1.reshape(-1, 6)

array([[2, 2, 2, 3, 3, 3]])

In [39]:
arr1.flatten()

array([2, 2, 2, 3, 3, 3])