### scikit-learn 설치

In [14]:
import sklearn

In [15]:
sklearn.__version__

'0.24.1'

### [실습] 내장 데이터셋 iris 실습

#### [1] 데이터 준비

In [16]:
# 필요한 모듈 로딩
from sklearn.datasets import load_iris

In [17]:
iris = load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [18]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [19]:
# 속성 정보 확인
for k, v in iris.items():
    print(f'[{k}] => {v}')

[data] => [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [

In [20]:
type(iris['data']), type(iris['target']), iris['feature_names']

(numpy.ndarray,
 numpy.ndarray,
 ['sepal length (cm)',
  'sepal width (cm)',
  'petal length (cm)',
  'petal width (cm)'])

In [21]:
## pandas의 DataFrame 또는 Series로 반환 받기
#iris, label = load_iris(return_X_y = True, as_frame = True)

In [22]:
# type(iris), type(label)

#### [2] 학습용 데이터 + 테스트용 데이터 준비
- 좋은 방법 : 두 종류 ~ 세 종류 데이터 따로 존재
- 개선 방법 : 학습용 데이터를 분리해서 사용
- sklearn 제공 함수 : train_test_split()

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
# 입력 => 학습용 데이터, 학습용 라벨
# 출력 => 학습용 데이터, 테스트용 데이터, 학습용 라벨, 테스트용 라벨 : 80% : 20%
X_train, X_test, y_train, y_test, = train_test_split(iris['data'], iris['target'], test_size = 0.2, random_state = 11)

In [25]:
len(X_train), len(X_test), len(y_train), len(y_test)

(120, 30, 120, 30)

In [26]:
# 입력 => 학습용 데이터, 학습용 라벨
# 출력 => 학습용 데이터, 검증용 데이터, 학습용 라벨, 검증용 라벨 : 80% : 20%
X_train, X_val, y_train, y_val, = train_test_split(X_train, y_train, test_size = 0.2)

In [27]:
len(X_train), len(X_val), len(y_train), len(y_val)

(96, 24, 96, 24)

#### [3] 학습 모델 생성
- 데이터 구조 : feature + label => 지도학습
- label type : 범주형           => 분류
- 분류 학습 방법 => 생성

In [28]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

In [29]:
# 학습 모델 생성
#model = DecisionTreeClassifier()
#model = SVC()
model = KNeighborsClassifier()

#### [4] 학습 <-- 학습용 데이터 사용
- 모델객체변수명.fit( 학습용 데이터, 학습용 라벨 )

In [30]:
model.fit(X_train, y_train)

KNeighborsClassifier()

#### [5] 성능 평가 <-- 테스트 데이터 사용
- 모델객체변수명.score(테스트 데이터, 테스트 라벨)
 * 모델에 테스트 데이터를 입력 ==> 예측라벨 vs 테스트 라벨

In [31]:
model.score(X_test, y_test)

0.9666666666666667

- 성능평가 모듈 : sklearn.metrics
- 성능평가 함수 : accuracy_score()

In [32]:
from sklearn.metrics import accuracy_score

In [33]:
# 테스트 데이터에 대한 예측값 추출 => 모델객체변수명.predict(테스트 데이터)
y_pre = model.predict(X_test)

In [34]:
type(X_test), X_test.shape

(numpy.ndarray, (30, 4))

In [35]:
y_pre, len(y_pre)

(array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
        0, 1, 0, 0, 2, 1, 0, 1]),
 30)

In [36]:
# 정답 비율
# accuracy_score(정답 라벨, 예측 라벨)
accuracy_score(y_test, y_pre)

0.9666666666666667

In [37]:
# 정답 갯수
accuracy_score(y_test, y_pre, normalize = False)

29

In [38]:
# 임의의 데이터 => [1.2, 3.2, 0.4, 2.9]
new_data = [1.2, 3.2, 0.4, 2.9]
model.predict([new_data])

array([0])

In [39]:
import numpy as np

In [40]:
new_data = np.array([1.2, 3.2, 0.4, 2.9]).reshape(1, -1)
new_data.shape

(1, 4)

In [41]:
model.predict(new_data)

array([0])