### [실습] 내장 데이터셋 breast_cancer 실습

#### [1] 데이터 준비

In [1]:
# 유방암 데이터 로딩
from sklearn.datasets import load_breast_cancer
dataset = load_breast_cancer()

In [2]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [3]:
# 속성 정보 확인
for k, v in dataset.items():
    print(f'[{k}] => {v}')

[data] => [[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]
[target] => [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 1 0 0 1 0 0 1 1 1 1 0 1 0 0 1 1 1 1 0 1 0 0
 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 1 0 1 1 0 0 1 1 1 0 0 1 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 1 0 0 0 1 0 0 1 1 1 0 0 1 0 1 0 0 1 0 0 1 1 0 1 1 0 1 1 1 1 0 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 0 0 1 0 1 1 0 0 1 1 0 0 1 1 1 1 0 1 1 0 0 0 1 0
 1 0 1 1 1 0 1 1 0 0 1 0 0 0 0 1 0 0 0 1 0 1 0 1 1 0 1 0 0 0 0 1 1 0 0 1 1
 1 0 1 1 1 1 1 0 0 1 1 0 1 1 0 0 1 0 1 1 1 1 0 1 1 1 1 1 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 1 1 1 1 0 1 0 1 1 0 1 1 0 

In [4]:
type(dataset['data']), type(dataset['target']), dataset['feature_names']

(numpy.ndarray,
 numpy.ndarray,
 array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'))

#### [2] 학습용 데이터 + 테스트용 데이터 준비
- 좋은 방법 : 두 종류 ~ 세 종류 데이터 따로 존재
- 개선 방법 : 학습용 데이터를 분리해서 사용
- sklearn 제공 함수 : train_test_split()

In [5]:
from sklearn.model_selection import train_test_split

In [6]:
# 입력 => 학습용 데이터, 학습용 라벨
# 출력 => 학습용 데이터, "테스트"용 데이터, 학습용 라벨, "테스트"용 라벨 : 80% : 20%
X_train, X_test, y_train, y_test = train_test_split(dataset['data'], dataset['target'], test_size = 0.2, random_state = 11)

In [7]:
len(X_train), len(X_test), len(y_train), len(y_test)

(455, 114, 455, 114)

In [8]:
# 입력 => 학습용 데이터, 학습용 라벨
# 출력 => 학습용 데이터, "검증용" 데이터, 학습용 라벨, "검증용" 라벨 : 80% : 20%
X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size = 0.2)

In [9]:
len(X_train), len(X_test), len(y_train), len(y_test)

(364, 91, 364, 91)

#### [3] 학습 모델 생성
- 데이터 구조 : feature + label => 지도학습
- label type : 범주형           => 분류
- 분류 학습 방법 => 생성

✔️ Decision Tree 모델

In [32]:
# 결정 나무 분류
from sklearn.tree import DecisionTreeClassifier

# 랜덤 포레스트
from sklearn.ensemble import RandomForestClassifier

# Support Vector Machine (SVM)
from sklearn import svm

# Stochastic Gradient Descent Classifier (SGD)
from sklearn.linear_model import SGDClassifier

In [11]:
# 학습 모델 생성
model_dt = DecisionTreeClassifier()
model_rf = RandomForestClassifier()
model_svm = svm.SVC()


#### [4] 학습 <-- 학습용 데이터 사용
- 모델객체변수명.fit( 학습용 데이터, 학습용 라벨 )

In [12]:
model_dt.fit(X_train, y_train)

DecisionTreeClassifier()

In [13]:
model_rf.fit(X_train, y_train)

RandomForestClassifier()

In [25]:
model_svm.fit(X_train, y_train)

SVC()

#### [5] 성능 평가 <-- 테스트 데이터 사용
- 모델객체변수명.score(테스트 데이터, 테스트 라벨)
 * 모델에 테스트 데이터를 입력 ==> 예측라벨 vs 테스트 라벨

In [14]:
model_dt.score(X_test, y_test)

0.9230769230769231

In [15]:
model_rf.score(X_test, y_test)

0.9560439560439561

In [26]:
model_svm.score(X_test, y_test)

0.8901098901098901

- 성능평가 모듈 : sklearn.metrics
- 성능평가 함수 : accuracy_score()

In [16]:
from sklearn.metrics import accuracy_score

In [28]:
# 테스트 데이터에 대한 예측값 추출 => 모델객체변수명.predict(테스트 데이터)
y_pre_dt = model_dt.predict(X_test)
y_pre_rf = model_rf.predict(X_test)
y_pre_svm = model_svm.predict(X_test)

In [18]:
type(X_test), X_test.shape

(numpy.ndarray, (91, 30))

In [19]:
y_pre_dt, len(y_pre_dt)

(array([1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1,
        1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1,
        0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0,
        0, 1, 1]),
 91)

In [21]:
# 정답 비율
# accuracy_score(정답 라벨, 예측 라벨)
accuracy_score(y_test, y_pre_dt)

0.9230769230769231

In [22]:
accuracy_score(y_test, y_pre_rf)

0.9560439560439561

In [30]:
accuracy_score(y_test, y_pre_svm)

0.8901098901098901

In [23]:
# 정답 갯수
accuracy_score(y_test, y_pre_dt, normalize = False)

84

In [24]:
accuracy_score(y_test, y_pre_rf, normalize = False)

87

In [31]:
accuracy_score(y_test, y_pre_svm, normalize = False)

81