### Pytorch

#### pytorch의 일반적인 import 형태

In [1]:
import torch

#### ✨scala (0D tensor)
: 하나의 텐서를 가지는 0차원 텐서

In [2]:
import numpy as np
data1 = np.array(10)
print(data1, data1.ndim, data1.shape) # ndim : axis 축, shape : 행렬의 차원

10 0 ()


#### ✨vector (1D tensor)

In [3]:
data1 = torch.FloatTensor([1, 2])
print(data1, data1.dim(), data1.shape)

data2 = torch.FloatTensor(3) # 임의의 3개의 원소를 가진 1D 텐서
print(data2, data2.dim(), data2.shape)

tensor([1., 2.]) 1 torch.Size([2])
tensor([ 0.0000e+00,  4.4766e+00, -3.2190e-34]) 1 torch.Size([3])


In [4]:
# matrix (2D tensor)
data3 = torch.FloatTensor(3, 2)
print(data3, data3.dim(), data3.shape)

data4 = torch.FloatTensor([ [1,2], [3,4], [5,6] ])
print(data4, data4.dim(), data4.shape)

tensor([[2.5961e+20, 1.0082e-08],
        [6.4836e-10, 5.2592e+22],
        [5.1891e-11, 7.1450e+31]]) 2 torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]]) 2 torch.Size([3, 2])


In [5]:
# 3D tensor
data5 = torch.FloatTensor(3, 2, 1)
print(data5, data5.dim(), data5.shape)

data6 = torch.FloatTensor([ [[1],[2]], [[3],[4]], [[5],[6]] ])
print(data6, data6.dim(), data6.shape)

tensor([[[0.0000e+00],
         [0.0000e+00]],

        [[0.0000e+00],
         [0.0000e+00]],

        [[0.0000e+00],
         [7.4269e-44]]]) 3 torch.Size([3, 2, 1])
tensor([[[1.],
         [2.]],

        [[3.],
         [4.]],

        [[5.],
         [6.]]]) 3 torch.Size([3, 2, 1])


In [6]:
# 밖에서부터 안쪽으로 텐서 선언 이해
data7 = torch.FloatTensor([ [1], [2], [3] ])
print(data7, data7.dim(), data7.shape)

data8 = torch.FloatTensor([ [1,2,3] ])
print(data8, data8.dim(), data8.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([[1., 2., 3.]]) 2 torch.Size([1, 3])


### Tensor 생성 주요 메서드
- torch.zeros(x, y, z): 0 값으로 shape 모양의 텐서 생성
- torch.ones(x, y, z): 1 값으로 shape 모양의 텐서 생성
- torch.rand(x, y, z): 0 부터 1 사이에 균일한 확률 분포로 랜덤한 값을 가진 (x, y) shape 의 텐서 생성
- torch.randn(x, y, z): 기댓값이 0이고, 표준편차가 1인 가우시안 표준 정규 분포를 따르는 랜덤값을 가진 (x, y) shape 의 텐서 생성
- torch.full((x, y, z), a): a 값으로, shape 모양의 텐서 생성
<br><br>
- torch.zeros_like(tensor): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 0 으로 이루어진 텐서 생성
- torch.ones_like(tensor): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 0 으로 이루어진 텐서 생성
- torch.rand_like(tensor): 0 부터 1 사이에 균일한 확률 분포로 랜덤한 값을 가진 (x, y) shape 의 텐서 생성
- torch.randn_like(tensor): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 randn() 의 랜덤값으로 채워진 텐서 생성
- torch.full_like(tensor, a): 인자로 들어간 tensor 객체와 동일 shape 를 가지되, 각 원소값은 a 값으로 이루어진 텐서 생성
<br><br>
- torch.empty(x, y, z): 특정 의도로 초기화 되지 않은 값을 가진 (x, y) shape 의 행렬 생성

> shape 은 여러 차원이 될 수 있음 
> 각 메서드에 dtype=type 인자를 넣어, 데이터 타입 명시 가능

#### ✨Tensor 데이터 타입

<img src="https://www.fun-coding.org/00_Images/pytorch-type.png">

In [7]:
import torch

data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.zeros(2, 2, dtype=torch.double)
data3 = torch.zeros(2, 2, 3, dtype=torch.half)
data4 = torch.zeros(2, 2, 3, 4)
data5 = torch.full((2,4), 10)

In [8]:
data5

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10]])

In [9]:
# check shape
print(data1.shape, data2.shape, data3.shape, data4.shape, data5.shape)

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [10]:
# dimension of array
print(data1.ndim, data2.ndim, data3.ndim, data4.ndim, data5.ndim)
print(data1.dim(), data2.dim(), data3.dim(), data4.dim(), data5.dim())

1 2 3 4 2
1 2 3 4 2


In [11]:
# check datatype
print(data1.dtype, data2.dtype, data3.dtype, data4.dtype, data5.dtype)

torch.float32 torch.float64 torch.float16 torch.float32 torch.int64


In [12]:
# check data size
print(data1.size(), data2.size(), data3.size(), data4.size(), data5.size())

torch.Size([2]) torch.Size([2, 2]) torch.Size([2, 2, 3]) torch.Size([2, 2, 3, 4]) torch.Size([2, 4])


In [13]:
# 각 원소값으로 직접 대입하여 tensor 선언
data6 = torch.FloatTensor([ [1,2], [3,4] ])
data7 = torch.FloatTensor([ [1,2,3], [4,5,6] ])
data8 = torch.FloatTensor([ [1,2,3], [4,5,6], [7,8,9] ])

# shape을 기반으로 tensor 선언
data9 = torch.FloatTensor(2, 3, 5)
data10 = torch.DoubleTensor(3, 3, 2, 4)
data11 = torch.LongTensor(4, 4)

In [14]:
data9

tensor([[[1.4542e+00, 7.0625e-43, 1.1421e-03, 7.0625e-43, 4.2878e+00],
         [7.0625e-43, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 1.4013e-45, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 9.8091e-45, 0.0000e+00]]])

In [15]:
# _like()로 tensor 생성
data12 = torch.full_like(data5, 20)

In [16]:
print(data5)
print(data12)

tensor([[10, 10, 10, 10],
        [10, 10, 10, 10]])
tensor([[20, 20, 20, 20],
        [20, 20, 20, 20]])


#### ✨reshape()
- 배열 구조 변경
- 원소 수를 유지하면서 텐서의 크기 변경할 때 많이 사용하며, 매우 중요함!

In [17]:
import torch

data1 = torch.DoubleTensor([ [1,2,3], [4,5,6] ])
print(data1, data1.shape)

data1 = data1.reshape(3, 2)
print(data1, data1.shape)

data1 = data1.reshape(1, -1)
print(data1, data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64) torch.Size([2, 3])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64) torch.Size([3, 2])
tensor([[1., 2., 3., 4., 5., 6.]], dtype=torch.float64) torch.Size([1, 6])


#### ✨view()
: 텐서 구조 변경

In [18]:
import torch

data1 = torch.DoubleTensor([
    [[1,2,3],
    [4,5,6]],
    [[7,8,9],
    [10,11,12]]
])
print(data1.shape, "높이(k):", data1.size(0), "너비(n):", data1.size(1), "깊이(m):", data1.size(2))

torch.Size([2, 2, 3]) 높이(k): 2 너비(n): 2 깊이(m): 3


In [19]:
data1 = data1.view(2, -1)
print(data1, data1.shape)

data1 = data1.view(-1, 3)
print(data1, data1.shape)

data1 = data1.view(3, 2, -1)
print(data1, data1.shape)

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.],
        [ 7.,  8.,  9., 10., 11., 12.]], dtype=torch.float64) torch.Size([2, 6])
tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=torch.float64) torch.Size([4, 3])
tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]], dtype=torch.float64) torch.Size([3, 2, 2])


#### ✨squeeze() : 텐서 차원 압축

In [20]:
data1 = torch.FloatTensor([ [1], [2], [3] ])
data2 = data1.squeeze()
print(data1, data1.dim(), data1.shape)
print(data2, data2.dim(), data2.shape)

tensor([[1.],
        [2.],
        [3.]]) 2 torch.Size([3, 1])
tensor([1., 2., 3.]) 1 torch.Size([3])


In [21]:
data4 = torch.randn(2, 1, 3, 4)
data4.squeeze().shape

torch.Size([2, 3, 4])

#### ✨unsqueeze() : 특정 위치에 1인 차원을 추가

In [22]:
data1 = torch.FloatTensor([[1,2,3], [4,5,6]])
print(data1, data1.dim(), data1.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) 2 torch.Size([2, 3])


In [23]:
data2 = data1.unsqueeze(0)
data3 = data2.unsqueeze(1)
print(data2, data2.dim(), data2.shape)
print(data3, data3.dim(), data3.shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.]]]) 3 torch.Size([1, 2, 3])
tensor([[[[1., 2., 3.],
          [4., 5., 6.]]]]) 4 torch.Size([1, 1, 2, 3])


#### ✨데이터 타입 변환 (type)

In [24]:
import torch

data1 = torch.zeros(2, dtype=torch.float)
data2 = torch.ones(2, 4, dtype=torch.double)
data3 = torch.rand(2, 2, 3, dtype=torch.half)
print(data1.dtype, data2.dtype, data3.dtype)

data1 = data1.type(torch.float32)
data2 = data2.type(torch.int)
data3 = data3.type(torch.double)
print(data1.dtype, data2.dtype, data3.dtype)

torch.float32 torch.float64 torch.float16
torch.float32 torch.int32 torch.float64


#### ✨T : 전치(transpose) 행렬
- 행과 열을 교환하여 얻는 행렬을 의미, $A^T$로 표현

In [25]:
print(data2)
data2 = data2.T
print(data2)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1],
        [1, 1],
        [1, 1]], dtype=torch.int32)


#### ✨numpy 와 pytorch
- PyTorch의 tensor와 numpy의 ndarray는 서로 변환 가능
    - 텐서객체.numpy() : tensor 객체를 ndarray 객체로 변환
    - torch.from_numpy(ndarray) : ndarray를 tensor 객체로 변환

In [26]:
import numpy as np

data1 = np.array([ [1,2], [3,4] ])
print(data1, type(data1))
data2 = torch.from_numpy(data1)
print(data2, type(data2))
data3 = data2.numpy()
print(data3, type(data3))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) <class 'torch.Tensor'>
[[1 2]
 [3 4]] <class 'numpy.ndarray'>


#### ✨arange() : 1차원 tensor 생성

In [27]:
torch.arange(5)

tensor([0, 1, 2, 3, 4])

In [28]:
torch.arange(1, 5)

tensor([1, 2, 3, 4])

In [29]:
torch.arange(1, 5, 2)

tensor([1, 3])

#### ✨linspace() : 범위 내 1차원 tensor 균등 생성

In [30]:
torch.linspace(1, 5, 4)

tensor([1.0000, 2.3333, 3.6667, 5.0000])

In [31]:
torch.linspace(1, 5, 10)

tensor([1.0000, 1.4444, 1.8889, 2.3333, 2.7778, 3.2222, 3.6667, 4.1111, 4.5556,
        5.0000])

#### ✨tensor 연산
- shape이 동일해야 하고, 행과 열이 같은 값끼리 연산

In [32]:
data1 = torch.full((2,2), 2)
data2 = torch.full((2,2), 3)

In [33]:
print(data1)
print(data2)

tensor([[2, 2],
        [2, 2]])
tensor([[3, 3],
        [3, 3]])


In [34]:
print(data1 + data2)
print(data1 - data2)
print(data1 * data2)
print(data1 / data2)

tensor([[5, 5],
        [5, 5]])
tensor([[-1, -1],
        [-1, -1]])
tensor([[6, 6],
        [6, 6]])
tensor([[0.6667, 0.6667],
        [0.6667, 0.6667]])


In [35]:
data1 = torch.full((3,2), 2)
data2 = torch.full((2,3), 1)
torch.matmul(data1, data2)

tensor([[4, 4, 4],
        [4, 4, 4],
        [4, 4, 4]])

#### ✨Tensor 연산 (브로드캐스팅)
- Tensor 간 연산이 broadcasting을 지원하면, Tensor는 동일한 차원으로 자동 확장됨
- shape이 다른 텐서끼리 연산할 때 shape을 맞춰줌 (데이터 확대)

In [37]:
data1 = torch.FloatTensor([ [1],[2],[3] ])
data2 = torch.FloatTensor([1,1,1])
data3 = data1 + data2

print(data1.shape, data2.shape, data3.shape)
print(data3)

torch.Size([3, 1]) torch.Size([3]) torch.Size([3, 3])
tensor([[2., 2., 2.],
        [3., 3., 3.],
        [4., 4., 4.]])


In [38]:
data1 = torch.FloatTensor(10,20,4)
data2 = torch.FloatTensor(20,4)
data3 = data1 + data2

print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 20, 4]) torch.Size([20, 4]) torch.Size([10, 20, 4])


In [39]:
data1 = torch.FloatTensor(10,2,5)
data2 = torch.FloatTensor(10,2,1)
data3 = data1 + data2

print(data1.shape, data2.shape, data3.shape)

torch.Size([10, 2, 5]) torch.Size([10, 2, 1]) torch.Size([10, 2, 5])


In [40]:
data1 = torch.FloatTensor(5)
data2 = torch.FloatTensor(10,10,1)
data3 = data1 + data2

print(data1.shape, data2.shape, data3.shape)

torch.Size([5]) torch.Size([10, 10, 1]) torch.Size([10, 10, 5])


#### ✨Tensor의 원소 접근 방법 (Indexing)

In [41]:
data3 = torch.FloatTensor([ [1,2,3], [4,5,6] ])
print(data3)
print(data3[1, 1])
print(data3[:, 1])
print(data3[:, :])
print(data3[:1, :2])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(5.)
tensor([2., 5.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.]])


#### ✨boolean indexting
- 조건 필터링과 검색을 동시에 할 수 있음

In [42]:
data1 = torch.FloatTensor([ [1,2,3],[5,5,5] ])
data2 = data1 > 3
print(data2)
print(data1[data2])
print(data1[(data1 > 3) & (data1 < 5)])

tensor([[False, False, False],
        [ True,  True,  True]])
tensor([5., 5., 5.])
tensor([])


#### ✨fancy indexing
- 다른 배열로 배열을 인덱싱할 수 있는 기능

In [43]:
data1 = torch.randn(4, 3)
print(data1)

tensor([[ 0.5730, -0.8958, -1.3144],
        [ 0.6169, -0.3903, -0.4328],
        [-1.2925, -1.3561,  0.0466],
        [-0.1641, -0.1002,  1.3041]])


In [45]:
# 특정 행 배열 추출하기
print(data1[[1,2,0]])
print(data1[ [1,-1] ])

tensor([[ 0.6169, -0.3903, -0.4328],
        [-1.2925, -1.3561,  0.0466],
        [ 0.5730, -0.8958, -1.3144]])
tensor([[ 0.6169, -0.3903, -0.4328],
        [-0.1641, -0.1002,  1.3041]])


In [49]:
# 특정 행과 열 추출하기
print(data1[ [1,2] ][:, [0,2] ])
print(data1[ [1,-1]][:, [0] ])

tensor([[ 0.6169, -0.4328],
        [-1.2925,  0.0466]])
tensor([[ 0.6169],
        [-0.1641]])


#### ✨텐서 복사 : 텐서객체.clone().detach()
- clone() : 기존 텐서객체의 내용을 복사한 텐서 생성
- detach() : 기존 텐서객체 그래프에서 분리된 텐서로 구성

In [50]:
data1 = torch.FloatTensor([ [1,2,3], [4,5,6] ])
print(data1)

data2 = data1[:2, :2]
print(data2)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])


In [52]:
# Shallow Copy (얕은 복사)
data2[1,1] = 4
print(data2)
print(data1)

tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 4., 6.]])


In [53]:
# Deep Copy (깊은 복사)
data1 = torch.FloatTensor([ [1,2,3], [4,5,6] ])
print(data1)

data2 = data1[:2,:2].clone().detach()
print(data2)

data2[1,1] = 4
print(data2)
print(data1)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2.],
        [4., 5.]])
tensor([[1., 2.],
        [4., 4.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


#### ✨tensor 조건 연산 : where()

In [54]:
# 조건에 맞는 값 indexing
data1 = torch.FloatTensor([7,2,0,4,1])
index = torch.where(data1 < 3)

print(index) # 조건에 맞는 인덱스 번호 리턴
print(data1[index])

(tensor([1, 2, 4]),)
tensor([2., 0., 1.])


In [55]:
# 조건에 맞는 값 특정 다른 값으로 변환
print(data1)
data2 = torch.where(data1 < 3, -1, 1) # 조건에 맞으면 -1, 틀리면 1
print(data2)

tensor([7., 2., 0., 4., 1.])
tensor([ 1, -1, -1,  1, -1])


In [56]:
# 다차원 배열에도 적용 가능
data1 = torch.FloatTensor([ [1,2,3], [4,5,6] ])
data2 = torch.where(data1 < 3, -1, 1)
print(data2)

tensor([[-1, -1,  1],
        [ 1,  1,  1]])


#### ✨tensor 데이터 분석

In [57]:
data1 = torch.FloatTensor([ [1,2,3], [4,5,6] ])
print(data1.min())
print(data1.max())
print(data1.sum())
print(data1.mean())
print(data1.var())
print(data1.std())
print(data1.argmin())
print(data1.argmax())

tensor(1.)
tensor(6.)
tensor(21.)
tensor(3.5000)
tensor(3.5000)
tensor(1.8708)
tensor(0)
tensor(5)


#### ✨텐서를 파일로 저장하고 불러오기
- 한 개의 텐서 저장
    - save() : 파일로 저장 가능

In [58]:
data1 = torch.linspace(1,5,4)
print(data1)
torch.save(data1, 'mydata1.pt')

tensor([1.0000, 2.3333, 3.6667, 5.0000])


- 한 개의 텐서 읽어오기
    - load() : 파일로 저장된 1차원 배열 읽어오기

In [59]:
data2 = torch.load('mydata1.pt')
print(data2)

tensor([1.0000, 2.3333, 3.6667, 5.0000])


- 한개 이상의 텐서 저장
    - 각 배열을 key=배열로 key값을 지정할 수 있음

In [60]:
data1 = torch.linspace(1,5,4)
data2 = torch.linspace(1,10,4)
data3 = torch.linspace(1,100,4)
print(data1)
print(data2)
print(data3)
datas = {'data1':data1, 'data2':data2, 'data3':data3}
torch.save(datas, 'mydata1.pt')

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


In [61]:
datas = torch.load('mydata1.pt')
print(datas['data1'])
print(datas['data2'])
print(datas['data3'])

tensor([1.0000, 2.3333, 3.6667, 5.0000])
tensor([ 1.,  4.,  7., 10.])
tensor([  1.,  34.,  67., 100.])


In [62]:
type(datas)

dict