### ✨Raw-level Linear Layer 구현

In [1]:
import torch

x = torch.FloatTensor(4)   # 입력
W = torch.FloatTensor(4,3) # 가중치
b = torch.FloatTensor(3)   # 편향

In [2]:
# Linear Layer
def linearfunction(x,W,b):
    y = torch.matmul(x, W) + b
    return y

In [3]:
print('W', W.shape, 'x', x.shape, 'b', b.shape)

W torch.Size([4, 3]) x torch.Size([4]) b torch.Size([3])


In [4]:
y = linearfunction(x, W, b)
y.shape

torch.Size([3])

### ✨nn.Module 기반, Linear Layer 구현
- 신경망 모델 클래스를 만들고, nn.Module을 상속받음
- _  _init_ _ 에서 신경망 계층 초기화 선언
- forward()메서드에서 입력 데이터에 대한 연산 정의

In [5]:
import torch
import torch.nn as nn

In [6]:
class NeuralNetwork(nn.Module):
    def __init__(self):
        super().__init__()
        self.W = torch.FloatTensor(4,3)
        self.b = torch.FloatTensor(3)
        
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [7]:
x = torch.FloatTensor(4)  # input
mylinear = NeuralNetwork()
y = mylinear(x)

In [8]:
print(y, y.shape)

tensor([0., 0., 0.]) torch.Size([3])


In [12]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.W = torch.FloatTensor(input_dim, output_dim)
        self.b = torch.FloatTensor(output_dim)
        
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [14]:
x = torch.FloatTensor(15)
mylinear = NeuralNetwork(15, 3)
y = mylinear(x)
print(y, y.shape)

tensor([7.4063e-04, 3.8943e-10, 1.7263e-04]) torch.Size([3])


In [15]:
# 파라미터 등록이 되어있지 않음
for param in mylinear.parameters():
    print(param)

### ✨nn.Module 기반, nn.Parameter 등록하기

In [16]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
        self.b = nn.Parameter(torch.FloatTensor(output_dim))
        
    def forward(self, x):
        y = torch.matmul(x, self.W) + self.b
        return y

In [17]:
x = torch.FloatTensor(4)
mylinear = NeuralNetwork(4, 3)
y = mylinear(x)
print(y, y.shape)

tensor([1.0286e-38, 1.0653e-38, 1.0469e-38], grad_fn=<AddBackward0>) torch.Size([3])


In [18]:
for param in mylinear.parameters():
    print(param)

Parameter containing:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], requires_grad=True)
Parameter containing:
tensor([1.0286e-38, 1.0653e-38, 1.0469e-38], requires_grad=True)


### ✨nn.Linear() 클래스

In [19]:
mylinear = nn.Linear(4,3)
y = mylinear(x)
print(y, y.shape)

tensor([ 0.0981,  0.0134, -0.0143], grad_fn=<AddBackward0>) torch.Size([3])


In [20]:
for param in mylinear.parameters():
    print(param)

Parameter containing:
tensor([[-0.4560,  0.0498,  0.4587,  0.0359],
        [ 0.3003,  0.4133,  0.0492,  0.2462],
        [ 0.2936, -0.2134, -0.4071,  0.4041]], requires_grad=True)
Parameter containing:
tensor([ 0.0981,  0.0134, -0.0143], requires_grad=True)


### ✨Pytorch 신경망 모델과 nn.Linear

In [21]:
import torch
import torch.nn as nn

class NeuralNetwork(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear = nn.Linear(input_dim, output_dim)
        
    def forward(self, x):
        y = self.linear(x)
        return y

In [22]:
mylinear = NeuralNetwork(4,3)
y = mylinear(x)
print(y, y.shape)

tensor([-0.0957, -0.3781,  0.1692], grad_fn=<AddBackward0>) torch.Size([3])


In [23]:
for param in mylinear.parameters():
    print(param)

Parameter containing:
tensor([[-0.3840,  0.3968,  0.2699, -0.3201],
        [-0.2326,  0.3688, -0.1214,  0.1142],
        [ 0.1392, -0.0338, -0.4593,  0.3743]], requires_grad=True)
Parameter containing:
tensor([-0.0957, -0.3781,  0.1692], requires_grad=True)
