#### 딥러닝 기초 개념

- w : weight(가중치)
- b : bias(편향)
- neural network : hidden layer 존재
- feature extraction(특성 추출) : 프로그램이 알아서 특성을 추출함
- node : 숫자 = X(연결된 노드의 값) * w(가중치)
- 오차 : predict - real
- loss function(오차 계산) : sum(오차^2)/n 사용  => 최소화!

#### -------------------------------------------------------------------------
##### 활성함수 (activation function)
* 시그모이드 함수(sigmoid function)
* 탄젠트 함수 (tangent function)
* --> 비선형 예측 (non-linearity)

#### -------------------------------------------------------------------------
##### 최적의 w 찾기
* 첫번 째 w는 랜덤
* 경사하강법 (Gradient Descent) : w - w의 접선의 기울기(w1이 총손실에 미치는 영향)
* 극소점이 아닌 점(local minima)을 찾을 경우가 존재 ==> w - (기울기 * learning rate)
* learning rate(alpha) optimizer : Momentum(가속도 유지), AdaGrad(자주 변하는 w 작게, 자주 변하면 크게), ★Adam

#### -------------------------------------------------------------------------
##### Tensor
* 행렬로 input / w값 저장 가능 -> node값 계산식 쉬워짐

In [3]:
import tensorflow as tf

# 기본 텐서 : 리스트 개념
텐서 = tf.constant(3)
print(텐서)

In [22]:
텐서1 = tf.constant([3, 4, 5])
텐서2 = tf.constant([6, 7, 8])

In [10]:
텐서3 = tf.constant([[1, 2], [3, 4]])
텐서3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [12]:
# 행렬 계산
# - tf.add(), tf.subtract(), tf.divide(), tf.multiply(), tf.matmul()
print(tf.add(텐서1, 텐서2))
print(텐서1 / 텐서2)

tf.Tensor([ 9 11 13], shape=(3,), dtype=int32)
tf.Tensor([0.5        0.57142857 0.625     ], shape=(3,), dtype=float64)


In [16]:
# tf.zeros() : 0만 담긴 텐서 생성
텐서4 = tf.zeros([2, 2, 3])   # 3개의 데이터를 담은 세트 2개 생성 후 그 세트를 또 2개 생성
print(텐서4)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]], shape=(2, 2, 3), dtype=float32)


In [18]:
print(텐서1.shape)
print(텐서3.shape)

(3,)
(2, 2)


In [21]:
# tensor의 datatype
# - 정수 : int
# - 실수 : float
print(텐서1)

tf.Tensor([3. 4. 5.], shape=(3,), dtype=float32)


In [27]:
# weight 저장 -> Variable 만들기
# 변경이 쉬움
w = tf.Variable(1.0)
#               -> 초기값

# 값을 불러올 때 -> numpy() 사용
print(w.numpy())

# 값 수정 -> assign() 사용
w.assign(2)
print(w.numpy())

1.0
2.0


In [29]:
#딥러닝으로 간단한 수학 문제 풀기
# - 키와 신발사이즈는 관련이 있을까?
키 = [170, 180, 175, 160]
신발 = [260, 270, 265, 255]

## 예시 y = a * 170 + b  -> a, b를 찾는 것이 목표!

In [34]:
# 키로 신발사이즈 추론해보기
height = 170
shoe = 260

# shoe = height * a + b

a = tf.Variable(0.1)
b = tf.Variable(0.2)

def lossFunc():
    predict = height * a + b
    return tf.square(260 - predict)

# 경사하강법을 이용해 w값(a, b) 업데이트
# - gradient 자동으로 설정
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

for i in range(300):
    opt.minimize(lossFunc, var_list=[a, b])
#                               -> 경사하강법으로 업데이트 할 w 입력
    print(a.numpy(), b.numpy())

0.20000002 0.3
0.299743 0.399743
0.39902854 0.49902856
0.4976288 0.59762883
0.5952905 0.6952905
0.69173086 0.7917309
0.78663594 0.88663596
0.8796619 0.9796619
0.9704343 1.0704342
1.0585508 1.1585507
1.1435848 1.2435848
1.2250917 1.3250916
1.3026174 1.4026173
1.3757098 1.4757097
1.4439315 1.5439314
1.5068752 1.6068751
1.5641792 1.6641791
1.615542 1.715542
1.6607362 1.7607361
1.6996179 1.7996178
1.7321334 1.8321333
1.7583209 1.8583208
1.7783084 1.8783083
1.7923075 1.8923074
1.800605 1.900605
1.803553 1.9035529
1.8015567 1.9015566
1.7950644 1.8950644
1.7845562 1.884556
1.7705342 1.8705341
1.7535139 1.8535138
1.7340164 1.8340163
1.7125608 1.8125607
1.689658 1.789658
1.6658051 1.765805
1.6414793 1.7414792
1.6171328 1.7171327
1.5931883 1.6931882
1.5700338 1.6700337
1.5480187 1.6480186
1.5274498 1.6274498
1.5085886 1.6085885
1.4916484 1.5916483
1.4767939 1.5767938
1.4641396 1.5641395
1.453751 1.5537509
1.445646 1.545646
1.4397974 1.5397973
1.4361359 1.5361358
1.4345546 1.5345545
1.4349129 1.5

In [35]:
# final predict value
170 * 1.52 + 1.62

260.02