### 02 Tensorflow (텐서플로)

📌텐서플로

tensorflow 불러오기

In [3]:
import tensorflow as tf

📌 텐서플로2 주요 특징

2-1 즉시 실행

In [72]:
# 실행 모드 확인
print(tf.executing_eagerly())

True


In [73]:
a = 1
b = 2
c = tf.math.add(a, b)
print(c)

tf.Tensor(3, shape=(), dtype=int32)


In [74]:
c.numpy()

3

2-2 고수준 API 지원

2-3 자동 미분

📌 텐서플로 자료구조

3-1 스칼라(Scalar)

In [4]:
# 스칼라 정의하기
a = tf.constant(1)
b = tf.constant(2)

print('a: ', a)
print('b: ', b)

a:  tf.Tensor(1, shape=(), dtype=int32)
b:  tf.Tensor(2, shape=(), dtype=int32)


In [5]:
# rank 확인
print(tf.rank(a))

tf.Tensor(0, shape=(), dtype=int32)


In [6]:
# 자료형 변환
a = tf.cast(a, tf.float32)
b = tf.cast(b, tf.float32)

print(a.dtype)
print(b.dtype)

<dtype: 'float32'>
<dtype: 'float32'>


In [7]:
# 덧셈
c = tf.math.add(a, b)
print('result: ', c)            # 1 + 2의 결과
print('rank: ', tf.rank(c))     # 스칼라 텐서 --> 랭크 = 0

result:  tf.Tensor(3.0, shape=(), dtype=float32)
rank:  tf.Tensor(0, shape=(), dtype=int32)


In [8]:
# 뺄셈
print(tf.math.subtract(a, b))

tf.Tensor(-1.0, shape=(), dtype=float32)


In [9]:
# 곱셈
print(tf.math.multiply(a, b))

tf.Tensor(2.0, shape=(), dtype=float32)


In [10]:
# 나눗셈
print(tf.math.divide(a, b))

tf.Tensor(0.5, shape=(), dtype=float32)


In [11]:
# 나눗셈(나머지) --> 파이썬 연산자 %
print(tf.math.mod(a, b))

tf.Tensor(1.0, shape=(), dtype=float32)


In [12]:
# 나눗셈(몫) --> 파이썬 연산자 //
print(tf.math.floordiv(a, b))

tf.Tensor(0.0, shape=(), dtype=float32)


3-2 벡터(Vector)

In [13]:
import numpy as np

In [25]:
# 1차원 벡터 정의
py_list = [10., 20., 30.]
num_arr = np.array([10., 10., 10.])

In [26]:
# 텐서 변환
vec1 = tf.constant(py_list, dtype=tf.float32)
vec2 = tf.constant(num_arr, dtype=tf.float32)

In [27]:
# 텐서 출력
print(vec1)
print(vec2)

tf.Tensor([10. 20. 30.], shape=(3,), dtype=float32)
tf.Tensor([10. 10. 10.], shape=(3,), dtype=float32)


In [28]:
# 랭크 확인
print(tf.rank(vec1))
print(tf.rank(vec2))

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [29]:
# 덧셈 함수
add1 = tf.math.add(vec1, vec2)
print('result: ', add1)
print('rank: ', tf.rank(add1))

result:  tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [30]:
# 덧셈 연산자
add2 = vec1 + vec2
print('result: ', add2)
print('rank: ', tf.rank(add2))

result:  tf.Tensor([20. 30. 40.], shape=(3,), dtype=float32)
rank:  tf.Tensor(1, shape=(), dtype=int32)


In [31]:
# tf.math 모듈 함수
print(tf.math.subtract(vec1, vec2))
print(tf.math.multiply(vec1, vec2))
print(tf.math.divide(vec1, vec2))
print(tf.math.mod(vec1, vec2))
print(tf.math.floordiv(vec1, vec2))

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [32]:
# 파이썬 연산자
print(vec1 - vec2)
print(vec1 * vec2)
print(vec1 / vec2)
print(vec1 % vec2)
print(vec1 // vec2)

tf.Tensor([ 0. 10. 20.], shape=(3,), dtype=float32)
tf.Tensor([100. 200. 300.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
tf.Tensor([0. 0. 0.], shape=(3,), dtype=float32)
tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)


In [33]:
# 합계 구하기
print(tf.reduce_sum(vec1))
print(tf.reduce_sum(vec2))

tf.Tensor(60.0, shape=(), dtype=float32)
tf.Tensor(30.0, shape=(), dtype=float32)


In [34]:
# 거듭제곱
print(tf.math.square(vec1))

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [35]:
# 거듭제곱(파이썬 연산자)
print(vec1 ** 2)

tf.Tensor([100. 400. 900.], shape=(3,), dtype=float32)


In [36]:
# 제곱근
print(tf.math.sqrt(vec2))

tf.Tensor([3.1622777 3.1622777 3.1622777], shape=(3,), dtype=float32)


In [37]:
# 제곱근(파이썬 연산자)
print(vec2 ** 0.5)

tf.Tensor([3.1622777 3.1622777 3.1622777], shape=(3,), dtype=float32)


In [38]:
# 브로드캐스팅 연산
print(vec1 + 1)

tf.Tensor([11. 21. 31.], shape=(3,), dtype=float32)


3-3 행렬(Matrix)

In [39]:
# 2차원 배열 정의
list_of_list = [[10, 20], [30, 40]]

In [40]:
# 텐서 변환
mat1 = tf.constant(list_of_list)

In [41]:
# 랭크 확인
print(tf.rank(mat1))

tf.Tensor(2, shape=(), dtype=int32)


In [42]:
# 텐서 출력
print('mat1: ', mat1)

mat1:  tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)


In [43]:
# 1차원 벡터 정의
vec1 = tf.constant([1, 0])
vec2 = tf.constant([-1, 2])

In [44]:
# 텐서 변환 - stack 함수로 1차원 배열을 위아래로 쌓기
mat2 = tf.stack([vec1, vec2])

In [45]:
# 랭크 확인
print(tf.rank(mat2))

tf.Tensor(2, shape=(), dtype=int32)


In [46]:
# 텐서 출력
print('mat2: ', mat2)

mat2:  tf.Tensor(
[[ 1  0]
 [-1  2]], shape=(2, 2), dtype=int32)


In [47]:
# element-by-element (같은 위치에 있는 원소들끼리 짝을 지어 계산)
element_mul = tf.math.multiply(mat1, mat2)

print('result: ', element_mul)
print('rank: ', tf.rank(element_mul))

result:  tf.Tensor(
[[ 10   0]
 [-30  80]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [48]:
# 브로드캐스팅 연산
element_bc = tf.math.multiply(mat1, 3)

print('result: ', element_bc)
print('rank: ', tf.rank(element_bc))

result:  tf.Tensor(
[[ 30  60]
 [ 90 120]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [49]:
# 행렬곱 연산
mat_mul = tf.matmul(mat1, mat2)

print('result: ', mat_mul)
print('rank: ', tf.rank(mat_mul))

result:  tf.Tensor(
[[-10  40]
 [-10  80]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [50]:
# 덧셈
add1 = tf.math.add(mat1, mat2)

print('result: ', add1)
print('rank: ', tf.rank(add1))

result:  tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [51]:
# 덧셈 연산자
add2 = mat1 + mat2

print('result: ', add2)
print('rank: ', tf.rank(add2))

result:  tf.Tensor(
[[11 20]
 [29 42]], shape=(2, 2), dtype=int32)
rank:  tf.Tensor(2, shape=(), dtype=int32)


In [52]:
# 텐서를 넘파이로 변환
np_arr = mat_mul.numpy()

print(type(np_arr))
print(np_arr)

<class 'numpy.ndarray'>
[[-10  40]
 [-10  80]]


3-4 고차원 텐서

In [53]:
# 2차원 배열 정의
mat1 = [[1, 2, 3, 4],
        [5, 6, 7, 8]]

mat2 = [[9, 10, 11, 12],
        [13, 14, 15, 16]]

mat3 = [[17, 18, 19, 20],
        [21, 22, 23, 24]]

In [55]:
# 텐서 변환 - constant 함수에 3차원 배열 입력
tensor1 = tf.constant([mat1, mat2, mat3])

In [56]:
# 랭크 확인
print('rank: ', tf.rank(tensor1))

rank:  tf.Tensor(3, shape=(), dtype=int32)


In [57]:
# 텐서 출력
print('tensor1: ', tensor1)

tensor1:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [59]:
# 텐서 변환 - stack 함수로 2차원 배열을 위아래로 쌓기
tensor2 = tf.stack([mat1, mat2, mat3])

In [60]:
# 랭크 확인
print('rank: ', tf.rank(tensor2))

rank:  tf.Tensor(3, shape=(), dtype=int32)


In [61]:
# 텐서 출력
print('tensor2: ', tensor2)

tensor2:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [62]:
# 1차원 배열 정의
vec1 = [1, 2, 3, 4]
vec2 = [5, 6, 7, 8]
vec3 = [9, 10, 11, 12]
vec4 = [13, 14, 15, 16]
vec5 = [17, 18, 19, 20]
vec6 = [21, 22, 23, 24]

In [63]:
# 1차원 배열을 원소로 갖는 2차원 배열 정의
arr = [[vec1, vec2],
       [vec3, vec4],
       [vec5, vec6]]

In [64]:
# 텐서 변환
tensor3 = tf.constant(arr)

In [65]:
# 랭크 확인
print('rank: ', tf.rank(tensor3))

rank:  tf.Tensor(3, shape=(), dtype=int32)


In [66]:
# 텐서 출력
print('tensor3: ', tensor3)

tensor3:  tf.Tensor(
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]], shape=(3, 2, 4), dtype=int32)


In [69]:
# 랭크-4 텐서 만들기
tensor4 = tf.stack([tensor1, tensor2])

In [70]:
# 랭크 출력
print('rank: ', tf.rank(tensor4))

rank:  tf.Tensor(4, shape=(), dtype=int32)


In [71]:
# 텐서 출력
print('tensor4: ', tensor4)

tensor4:  tf.Tensor(
[[[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]


 [[[ 1  2  3  4]
   [ 5  6  7  8]]

  [[ 9 10 11 12]
   [13 14 15 16]]

  [[17 18 19 20]
   [21 22 23 24]]]], shape=(2, 3, 2, 4), dtype=int32)


📌인덱싱(Indexing)

In [3]:
# 벡터 정의
vec = tf.constant([10, 20, 30, 40, 50])
print(vec)

tf.Tensor([10 20 30 40 50], shape=(5,), dtype=int32)


In [4]:
print(vec[0])

tf.Tensor(10, shape=(), dtype=int32)


In [5]:
print(vec[-1])

tf.Tensor(50, shape=(), dtype=int32)


In [6]:
print(vec[:3])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [7]:
mat = tf.constant([[10, 20, 30],
                   [40, 50, 60]])
print(mat[0, 2])

tf.Tensor(30, shape=(), dtype=int32)


In [8]:
print(mat[0, :])

tf.Tensor([10 20 30], shape=(3,), dtype=int32)


In [10]:
print(mat[:, -1])

tf.Tensor([30 60], shape=(2,), dtype=int32)


In [11]:
print(mat[:, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [14]:
tensor = tf.constant([
    [[10, 20, 30],
     [40, 50, 60]],
     [[-10, -20, -30],
      [-40, -50, -60]],
])
print(tensor)

tf.Tensor(
[[[ 10  20  30]
  [ 40  50  60]]

 [[-10 -20 -30]
  [-40 -50 -60]]], shape=(2, 2, 3), dtype=int32)


In [15]:
print(tensor[0, :, :])

tf.Tensor(
[[10 20 30]
 [40 50 60]], shape=(2, 3), dtype=int32)


In [16]:
print(tensor[:, :2, :2])

tf.Tensor(
[[[ 10  20]
  [ 40  50]]

 [[-10 -20]
  [-40 -50]]], shape=(2, 2, 2), dtype=int32)


📌 형태 변환(tf.reshape)

In [28]:
# 텐서 정의
tensor = tf.constant(range(0, 24))
print(tensor)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [30]:
# (24, ) --> (3, 8)
tensor1 = tf.reshape(tensor, [3, 8])
print(tensor1)

tf.Tensor(
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]], shape=(3, 8), dtype=int32)


In [31]:
# (3, 8) --> (6, 4)
tensor2 = tf.reshape(tensor1, [-1, 4])
print(tensor2)

tf.Tensor(
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]], shape=(6, 4), dtype=int32)


In [32]:
# (6, 4) --> (24, )
tensor3 = tf.reshape(tensor2, [-1])
print(tensor3)

tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23], shape=(24,), dtype=int32)


In [33]:
# (24, ) --> (2, 3, 4)
tensor4 = tf.reshape(tensor3, [-1, 3, 4])
print(tensor4)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]], shape=(2, 3, 4), dtype=int32)


In [34]:
# (2, 3, 4) --> (3, 2, 4)
tensor5 = tf.reshape(tensor4, [3, 2, 4])
print(tensor5)

tf.Tensor(
[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]], shape=(3, 2, 4), dtype=int32)


In [35]:
# (3, 2, 4) --> (3, 2, 2, 2)
tensor6 = tf.reshape(tensor5, [3, 2, 2, 2])
print(tensor6)

tf.Tensor(
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]


 [[[16 17]
   [18 19]]

  [[20 21]
   [22 23]]]], shape=(3, 2, 2, 2), dtype=int32)


📌 변수(Variable)

In [16]:
# 텐서 정의
# constant : 상수, 변경 불가
tensor1 = tf.constant([[0, 1, 2],
                       [3, 4, 5]])
print(tensor1)

tf.Tensor(
[[0 1 2]
 [3 4 5]], shape=(2, 3), dtype=int32)


In [17]:
# Variable : 변수, 업데이트 가능
tensor_var1 = tf.Variable(tensor1)
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5]])>


In [19]:
print('이름: ', tensor_var1.name)
print("크기: ", tensor_var1.shape)
print('자료형: ', tensor_var1.dtype)
print('배열: ', tensor_var1.numpy())

이름:  Variable:0
크기:  (2, 3)
자료형:  <dtype: 'int32'>
배열:  [[0 1 2]
 [3 4 5]]


In [21]:
# assign() : 새로운 데이터 할당
tensor_var1.assign([[1, 1, 1],
                    [2, 2, 2]])
print(tensor_var1)

<tf.Variable 'Variable:0' shape=(2, 3) dtype=int32, numpy=
array([[1, 1, 1],
       [2, 2, 2]])>


In [23]:
# convert_to_tensor() : 텐서플로 변수 --> 텐서, 텐서의 크기와 값 변경 X
tensor2 = tf.convert_to_tensor(tensor_var1)
print(tensor2)

tf.Tensor(
[[1 1 1]
 [2 2 2]], shape=(2, 3), dtype=int32)


In [26]:
# name 속성
tensor_var2 = tf.Variable(tensor2, name = 'New Name')
print(tensor_var2.name)

New Name:0


In [27]:
# 연산
tensor_var1 + tensor_var2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 2, 2],
       [4, 4, 4]])>

📌 자동 미분 (Automatic Differentiation)

In [12]:
# y = 3 * x - 2 선형 관계를 갖는 데이터셋
g = tf.random.Generator.from_seed(2020)
X = g.normal(shape=(10,))
Y = 3 * X - 2

In [13]:
print('X: ', X.numpy())
print('Y: ', Y.numpy())

X:  [-0.20943771  1.2746525   1.213214   -0.17576952  1.876984    0.16379918
  1.082245    0.6199966  -0.44402212  1.3048344 ]
Y:  [-2.628313    1.8239574   1.6396422  -2.5273085   3.630952   -1.5086024
  1.2467351  -0.14001012 -3.3320663   1.9145031 ]


In [14]:
# Loss 함수 정의
def cal_mse(X, Y, a, b):
    Y_pred = a * X + b
    squared_error = (Y_pred - Y) ** 2
    mean_squared_error = tf.reduce_mean(squared_error)

    return mean_squared_error

In [15]:
# tf.GradientTape로 자동 미분 과정 기록
a = tf.Variable(0.0)
b = tf.Variable(0.0)

EPOCHS = 200

for epoch in range(1, EPOCHS+1):
    with tf.GradientTape() as tape:
        mse = cal_mse(X, Y, a, b)

    grad = tape.gradient(mse, {'a':a, 'b':b})
    d_a, d_b = grad['a'], grad['b']

    a.assign_sub(d_a * 0.05)
    b.assign_sub(d_b * 0.05)

    if epoch % 20 == 0:
        print('EPOCH %d - MSE: %.4f --- a:%.2f --- b:%.2f'%(epoch, mse, a, b))

EPOCH 20 - MSE: 1.1415 --- a:1.74 --- b:-0.75
EPOCH 40 - MSE: 0.2881 --- a:2.37 --- b:-1.37
EPOCH 60 - MSE: 0.0728 --- a:2.69 --- b:-1.68
EPOCH 80 - MSE: 0.0184 --- a:2.84 --- b:-1.84
EPOCH 100 - MSE: 0.0046 --- a:2.92 --- b:-1.92
EPOCH 120 - MSE: 0.0012 --- a:2.96 --- b:-1.96
EPOCH 140 - MSE: 0.0003 --- a:2.98 --- b:-1.98
EPOCH 160 - MSE: 0.0001 --- a:2.99 --- b:-1.99
EPOCH 180 - MSE: 0.0000 --- a:2.99 --- b:-1.99
EPOCH 200 - MSE: 0.0000 --- a:3.00 --- b:-2.00
